1. Importe numpy como np y vea la versión

In [2]:
import numpy as np
print(np.__version__)

1.22.4


2. ¿Cómo crear una matriz 1D?


In [4]:
matriz = np.arange(10)
matriz

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. ¿Cómo crear una matriz booleana?

In [5]:
a = np.full((3,3), True, dtype=bool)
a

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

4. ¿Cómo extraer elementos que satisfacen una condición dada de una matriz 1D?

In [7]:
b = np.arange(11)
b2 = (b % 2 != 0)
b[b2]

array([1, 3, 5, 7, 9])

5. ¿Cómo reemplazar los elementos que cumplen una condición con otro valor en la matriz numpy?
Nivel de dificultad: L1

P. Reemplace todos los números impares arrcon -1

In [10]:
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [16]:
b[b % 2 != 0] = -1
print(b)

[ 0 -1  2 -1  4 -1  6 -1  8 -1 10]


6. ¿Cómo reemplazar elementos que cumplen una condición sin afectar la matriz original?
Nivel de dificultad: L2

P. Reemplace todos los números impares en arr con -1 sin cambiararr

In [30]:
a = np.arange(11)
a1 = a.copy()
a1[b%2 != 0] = -1
print(a)
print(a1)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0 -1  2 -1  4 -1  6 -1  8 -1 10]


In [20]:
a = np.where(a % 2 != 0, -1, a)
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

7. ¿Cómo reformar una matriz?
Nivel de dificultad: L1

P. Convierta una matriz 1D en una matriz 2D con 2 filas

In [31]:
c = np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
c.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

8. ¿Cómo apilar dos matrices verticalmente?
Nivel de dificultad: L2

In [35]:
r = np.arange(10).reshape(2,-1)
p = np.repeat(1,10).reshape(2,-1)

In [38]:
np.concatenate([r,p], axis = 0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [37]:
np.vstack([r,p])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])